title: Image Upscaler Tool | whdzera
email: whdzera@gmail.com
baseurl: "/image-upscaler"
url: "" 
twitter_username: whdzera
github_username:  rokhimin/jekyll-nik-parse

permalink: /:title.rb
files: "/image-upscaler"
